version: "3"
services:
    mc:
        build: ./
        container_name: "DDS-docker-dev"
        ports:
            -   25565:25565
        volumes:
            -   DDS:/app
        environment:
             EULA: true
             OP: mari0theminer
volumes:
    DDS:
